// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmoFwMcil4lgWoZYFG7tvjqHyJl7I3x2I',
    appId: '1:1014701061344:web:11d16cc75da5db2214cc85',
    messagingSenderId: '1014701061344',
    projectId: 'emart-a2535',
    authDomain: 'emart-a2535.firebaseapp.com',
    storageBucket: 'emart-a2535.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVZYZHrml-anC0-RAdWhv-PNQo7Ca71M8',
    appId: '1:1014701061344:android:c02e40b7e038ba2e14cc85',
    messagingSenderId: '1014701061344',
    projectId: 'emart-a2535',
    storageBucket: 'emart-a2535.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmcXQYKYJKmAFzZ9ApVlE7xFmUTq1Gma8',
    appId: '1:1014701061344:ios:e0cb85dd0686333e14cc85',
    messagingSenderId: '1014701061344',
    projectId: 'emart-a2535',
    storageBucket: 'emart-a2535.appspot.com',
    iosBundleId: 'com.example.emart',
  );
}
